### ISSUE TITLE
Shortcode doesn't seem to do anything

### ISSUE THREAD

**Issue by brashrebel** [dragonslayerindustries/learndash-mailchimp#15]
I put [learndash_mc] on a page and viewed it as an admin, a student and logged out but nothing ever showed. How does it work?

**Comment by objectsweb** [comment]
It should work properly by adding the short-code anywhere then the subscription form should appear.  the reason were that you put the short-code inside the course itself and repeated it in another page so it made a conflict, But any way we will solve this one

**Comment by objectsweb** [comment]
Done.

**Comment by brashrebel** [comment]
Unfortunately I'm still confused by this. I put the shortcode into a regular page and not within the course at all. I view the page and it has no content and there's no subscription form.

**Comment by objectsweb** [comment]
- Please ensure that the short code is as following:
> [learndash_mc] --> at course page 
> [learndash_mc course_id="1"]  --> at any other page 

- Kindly check that auto subscribe checkbox not checked, because if it check no subscribe button will appear 

- Kindly check that course price type is free 

- Kindly check  if you are admin or not because admin as you know have access for all courses so he/ she will not see take this course button

**Comment by brashrebel** [comment]
Just did some testing and it looks closer but I'm still not getting exactly what I expect.

If I put `[learndash_mc]` into the body of a course and then view it as either a logged out visitor or a subscriber, nothing appears. However, if I turn on the "show form before course" option, the shortcode does output a Subscribe button. If that option is off, the button will not appear. I do not have auto subscribe on and am not an admin and the course is Free.

Also, if I use `[learndash_mc course_id="1"]` on a regular "page", a Subscribe button appears. If I'm logged in, clicking the button subscribes me. But if I am logged out, the button appears but clicking it does nothing.

Here are some suggested tweaks:

- [ ] Make the shortcode on course pages appear regardless of whether the "before" or other options are checked.

- [ ] Show an email address field for logged out users so they can subscribe without logging in.

- [ ] After successfully subscribing, the "Subscribed" text should not be in a button. It should just be text that says "Subscribed!" or "Success!" or "Thank you!" maybe with a check mark. But mostly it just shouldn't still be a button.

Is that possible? Thank you!

**Comment by objectsweb** [comment]
I'll pass to you a video record that describe the whole process from scratch in order to try it yourself.

Thanks you,

**Comment by objectsweb** [comment]
- Please check the video in the following link:
https://drive.google.com/file/d/0BxEM6iZoMCrrQkdhak80TDRZZjA/view?usp=sharing

Thank you.

**Comment by brashrebel** [comment]
@objectsweb good progress here. I mentioned two things in my last comment above. Those second two checkboxes are not completed currently. Are they possible?

**Comment by objectsweb** [comment]
- Show an email address field for logged out users so they can subscribe without logging in.
> This one delayed to be done in another phases.

- After successfully subscribing, the "Subscribed" text should not be in a button. It should just be text that says "Subscribed!" or "Success!" or "Thank you!" maybe with a check mark. But mostly it just shouldn't still be a button.
> Done, please check.

**Comment by d4mation** [comment]
> Show an email address field for logged out users so they can subscribe without logging in

Closing this Issue and opening one for the above
